name: Ximera Workflow

on:
  push:      

jobs:
  build-ximera:
    name: Build and preview Ximera Courses
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full 

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: | 
            **/*.html
            **/*.pdf
            **/*.svg
            **/*.aux
            **/*.xref
            **/*.toc
            !xmPictures/**
            !.git/**
            !.github/**
          key: ximera-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ximera-${{ github.ref_name }}-
            ximera-

      - name: Build and publish Ximera courses
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          XIMERA_URL: ${{ vars.XIMERA_URL }}
          XIMERA_NAME: ${{ vars.XIMERA_NAME }}*${{ github.ref_name }}
        run: |
          ls -alrt
          # git config --global --add safe.directory "$(pwd)"
          export COMMAND=./xmScripts/xmlatex.test
          ./xmScripts/xmlatex ghaction 
          echo "✅ Published to $XIMERA_URL$XIMERA_NAME " >> $GITHUB_STEP_SUMMARY

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: .
          retention-days: 3

  publish-ximera:
    name: Publish Ximera Courses
    needs: build-ximera # Waits for the build job to complete
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Serve
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          XIMERA_URL: ${{ vars.XIMERA_URL }}
          XIMERA_NAME: ${{ vars.XIMERA_NAME }}
        run: |
          chmod +x ./xmScripts/xmlatex*
          ls -alrt
          ls -al .git || echo NOK
          export COMMAND=./xmScripts/xmlatex.test
          ./xmScripts/xmlatex name         
          ./xmScripts/xmlatex serve         


